version: "2"
services:
  app:
    container_name: "zplimpress"
    restart: always
    build: .
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./:/usr/src/app/
    ports:
      - 3080:3080

networks:
  default:
    name: zpl_impress